### ISSUE TITLE
Update xanzy/go-cloudstack to support Cloudstack 4.12

### ISSUE THREAD

**Issue by joschi36** [swisstxt/cloudstack-cloud-controller-manager#10]
github.com/xanzy/go-cloudstack v2.7.0 is needed to support CloudStack 4.12 and onwards.

Because of this https://github.com/apache/cloudstack/issues/2528 and this https://github.com/apache/cloudstack/pull/3066 and this https://github.com/xanzy/go-cloudstack/commit/725c0d984f7067f1419096226e0ff1106a327e5b

**Comment by onitake** [comment]
This was addressed in 6405a6bbeb33d4f8c409e3c5f25b82c7140caa61
