### ISSUE TITLE
Verify documentation about integrating UDP and TCP-Proxy endpoints

### ISSUE THREAD

**Issue by onitake** [swisstxt/cloudstack-cloud-controller-manager#5]
It's not entirely clear if `hostNetwork: true` is really required for UDP and TCP-Proxy LoadBalancer endpoints.

Relevant lines: https://github.com/swisstxt/cloudstack-cloud-controller-manager/blame/master/README.md#L92-L93

@joschi36 Please confirm.

**Comment by onitake** [comment]
@joschi36 Is this still relevant?
I believe our setup is working without hostNetwork, or am I mistaken?

**Comment by joschi36** [comment]
not needed

**Comment by onitake** [comment]
All right, thanks!
